//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoneRV.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZoneRV.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Blank Debug Display.
        /// </summary>
        internal static string ZRV0001CodeAction {
            get {
                return ResourceManager.GetString("ZRV0001CodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes with in model namespaces should have a DebugDisplay.
        /// </summary>
        internal static string ZRV0001Description {
            get {
                return ResourceManager.GetString("ZRV0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should have a DebugDisplay.
        /// </summary>
        internal static string ZRV0001MessageFormat {
            get {
                return ResourceManager.GetString("ZRV0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Debug Display, should include data from members.
        /// </summary>
        internal static string ZRV0001Title {
            get {
                return ResourceManager.GetString("ZRV0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Displays should include data from members to provide useful information while debugging.
        /// </summary>
        internal static string ZRV0002DescriptionBadInterpolation {
            get {
                return ResourceManager.GetString("ZRV0002DescriptionBadInterpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Displays cannot be empty.
        /// </summary>
        internal static string ZRV0002DescriptionEmpty {
            get {
                return ResourceManager.GetString("ZRV0002DescriptionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Display argument is invalid.
        /// </summary>
        internal static string ZRV0002MessageFormat {
            get {
                return ResourceManager.GetString("ZRV0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Display value is invalid.
        /// </summary>
        internal static string ZRV0002Title {
            get {
                return ResourceManager.GetString("ZRV0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional fields cannot be created with complex expressions such as `card =&gt; card.Checklist.First().Checks` instead add the Checklist property seperately.
        /// </summary>
        internal static string ZRV0003Description {
            get {
                return ResourceManager.GetString("ZRV0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid expression, must use a simple non invoked expression to create an optional field.
        /// </summary>
        internal static string ZRV0003MessageFormat {
            get {
                return ResourceManager.GetString("ZRV0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Field should be expressed as simple property Expressions.
        /// </summary>
        internal static string ZRV0003Title {
            get {
                return ResourceManager.GetString("ZRV0003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression does not contain any properties with OptionalFieldAttribute and should be removed.
        /// </summary>
        internal static string ZRV0004 {
            get {
                return ResourceManager.GetString("ZRV0004", resourceCulture);
            }
        }
    }
}
