//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoneRV.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZoneRV.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Blank Debug Display.
        /// </summary>
        internal static string ZRV0001CodeAction {
            get {
                return ResourceManager.GetString("ZRV0001CodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes with in model namespaces should have a DebugDisplay.
        /// </summary>
        internal static string ZRV0001Description {
            get {
                return ResourceManager.GetString("ZRV0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should have a DebugDisplay.
        /// </summary>
        internal static string ZRV0001MessageFormat {
            get {
                return ResourceManager.GetString("ZRV0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Debug Display, should include data from members.
        /// </summary>
        internal static string ZRV0001Title {
            get {
                return ResourceManager.GetString("ZRV0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Displays should include data from members to provide useful information while debugging.
        /// </summary>
        internal static string ZRV0002DescriptionBadInterpolation {
            get {
                return ResourceManager.GetString("ZRV0002DescriptionBadInterpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Displays cannot be empty.
        /// </summary>
        internal static string ZRV0002DescriptionEmpty {
            get {
                return ResourceManager.GetString("ZRV0002DescriptionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Display argument is invalid.
        /// </summary>
        internal static string ZRV0002MessageFormat {
            get {
                return ResourceManager.GetString("ZRV0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Display value is invalid.
        /// </summary>
        internal static string ZRV0002Title {
            get {
                return ResourceManager.GetString("ZRV0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional properties cannot be created with complex expressions such as `card =&gt; card.Checklist.First().Checks` instead add the Checklist property seperately.
        /// </summary>
        internal static string ZRV0003Description {
            get {
                return ResourceManager.GetString("ZRV0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid expression, must use a simple non invoked expression to create an optional property.
        /// </summary>
        internal static string ZRV0003MessageFormat {
            get {
                return ResourceManager.GetString("ZRV0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional property should be expressed as simple property Expressions.
        /// </summary>
        internal static string ZRV0003Title {
            get {
                return ResourceManager.GetString("ZRV0003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression does not contain any properties with OptionalPropertyAttribute and should be removed.
        /// </summary>
        internal static string ZRV0004 {
            get {
                return ResourceManager.GetString("ZRV0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailing Properties on extression do not contain any properties with OptionalPropertyAttribute and should be removed.
        /// </summary>
        internal static string ZRV0005 {
            get {
                return ResourceManager.GetString("ZRV0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable names should follow set naming conventions based on their class type..
        /// </summary>
        internal static string ZRV0006Description {
            get {
                return ResourceManager.GetString("ZRV0006Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; objects should not cointain &apos;{1}&apos; in their name.
        /// </summary>
        internal static string ZRV0006MessageFormat {
            get {
                return ResourceManager.GetString("ZRV0006MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent Naming.
        /// </summary>
        internal static string ZRV0006Title {
            get {
                return ResourceManager.GetString("ZRV0006Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should not be used in DebugDisplay as it is optional.
        /// </summary>
        internal static string ZRV0007MessageFormat {
            get {
                return ResourceManager.GetString("ZRV0007MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use optional properties in DebugDisplay.
        /// </summary>
        internal static string ZRV0007Title {
            get {
                return ResourceManager.GetString("ZRV0007Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using &apos;is null&apos; or &apos;is not null&apos; instead of &apos;==&apos; or &apos;!=&apos; for null checks.
        /// </summary>
        internal static string ZRV0008MessageFormat {
            get {
                return ResourceManager.GetString("ZRV0008MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;is&apos; pattern for null checks.
        /// </summary>
        internal static string ZRV0008Title {
            get {
                return ResourceManager.GetString("ZRV0008Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async Method names should end with Async.
        /// </summary>
        internal static string ZRV0009Title {
            get {
                return ResourceManager.GetString("ZRV0009Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters with ExpectConstPropertiesFrom or ExpectConstAssociationsFrom attributes should use constants from the correct type..
        /// </summary>
        internal static string ZRVHS01Description {
            get {
                return ResourceManager.GetString("ZRVHS01Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Constants from are not valid here. Expected constant from &apos;{1}&apos; or string literal..
        /// </summary>
        internal static string ZRVHS01MessageFormat {
            get {
                return ResourceManager.GetString("ZRVHS01MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid constant usage in parameter.
        /// </summary>
        internal static string ZRVHS01Title {
            get {
                return ResourceManager.GetString("ZRVHS01Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters with ExpectConstPropertiesFrom or ExpectConstAssociationsFrom attributes should use constants over string literals when available..
        /// </summary>
        internal static string ZRVHS02Description {
            get {
                return ResourceManager.GetString("ZRVHS02Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant &apos;{0}.{1}&apos; should be used over string literal &apos;{2}&apos;..
        /// </summary>
        internal static string ZRVHS02MessageFormat {
            get {
                return ResourceManager.GetString("ZRVHS02MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Constant in parameter over string literal.
        /// </summary>
        internal static string ZRVHS02Title {
            get {
                return ResourceManager.GetString("ZRVHS02Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All HubSpotEntityBase must have an ObjectNameAttribute..
        /// </summary>
        internal static string ZRVHS03Title {
            get {
                return ResourceManager.GetString("ZRVHS03Title", resourceCulture);
            }
        }
    }
}
